"""Adicionar senha_temp em usuario

Revision ID: 1f191ff04732
Revises: 
Create Date: 2026-01-11 23:09:07.834704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f191ff04732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('carregado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagens_carregado_em'), ['carregado_em'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('token_prioridade', sa.String(length=64), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_token_prioridade'), ['token_prioridade'], unique=False)

    op.create_table('textos_entrada',
    sa.Column('id_texto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_texto')
    )
    with op.batch_alter_table('textos_entrada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_textos_entrada_chave'), ['chave'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('foto_perfil', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ocultar_dados', sa.Boolean(), nullable=False),
    sa.Column('tentativas_falhas', sa.Integer(), nullable=False),
    sa.Column('ultima_falha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('senha_temp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=False)

    op.create_table('cliente_cnpj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_cnpj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_cnpj_cnpj'), ['cnpj'], unique=True)

    op.create_table('cliente_cpf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('foto_perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('carregado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foto_perfil', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_perfil_carregado_em'), ['carregado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_foto_perfil_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('prestador_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=120), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestador_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestador_servico_cnpj'), ['cnpj'], unique=True)

    op.create_table('servico_prestado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_servico', sa.String(length=150), nullable=False),
    sa.Column('preco_servico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servico_prestado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servico_prestado_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_servico_prestado_nome_servico'), ['nome_servico'], unique=False)
        batch_op.create_index(batch_op.f('ix_servico_prestado_prestador_id'), ['prestador_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico_prestado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servico_prestado_prestador_id'))
        batch_op.drop_index(batch_op.f('ix_servico_prestado_nome_servico'))
        batch_op.drop_index(batch_op.f('ix_servico_prestado_criado_em'))

    op.drop_table('servico_prestado')
    with op.batch_alter_table('prestador_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestador_servico_cnpj'))

    op.drop_table('prestador_servico')
    with op.batch_alter_table('foto_perfil', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_perfil_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_foto_perfil_carregado_em'))

    op.drop_table('foto_perfil')
    op.drop_table('cliente_cpf')
    with op.batch_alter_table('cliente_cnpj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_cnpj_cnpj'))

    op.drop_table('cliente_cnpj')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_usuario_created_at'))

    op.drop_table('usuario')
    with op.batch_alter_table('textos_entrada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_textos_entrada_chave'))

    op.drop_table('textos_entrada')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_token_prioridade'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_email'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_criado_em'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagens_carregado_em'))

    op.drop_table('imagens')
    # ### end Alembic commands ###
